version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb-container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
